services:
  mysql-db:
    image: mysql:8.0
    container_name: bd_matricula
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=matriculadb
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: